version: 0.2

phases:
  install:
    commands:
      - echo "Deploy stage using CodeBuild standard image"

  pre_build:
    commands:
      - echo "Deploy phase started"
      - |
        IMAGE_TAG=$(cat imageTag.txt)
        echo "Deploying image tag: $IMAGE_TAG"
        export IMAGE_TAG
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 396462617987.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo "Pulling Docker image..."
      - docker pull 396462617987.dkr.ecr.ap-south-1.amazonaws.com/logicworks-multiregion-demo:$IMAGE_TAG
      - docker stop logicworks-demo || true
      - docker rm logicworks-demo || true
      - docker run -d --name logicworks-demo -p 80:80 396462617987.dkr.ecr.ap-south-1.amazonaws.com/logicworks-multiregion-demo:$IMAGE_TAG

  post_build:
    commands:
      - echo "Deployment completed successfully"

artifacts:
  files:
    - '**/*'
